on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  run-jmeter:
    runs-on: ubuntu-latest
 
    steps:
    
    - name: PerfAction for JMeter
      uses: QAInsights/PerfAction@v5.6.2
      with:
        test-plan-path: './RestAPI.jmx'
        
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: jmeter-results
        path: './result.jtl'
